import {test} from 'node:test';
import assert from 'node:assert/strict';
import {crearToken,leerToken,hashClave,verificarClave,crearHandler} from '../api/sunat.js';
const secreto='secreto-de-prueba';
function ejecutar(handler,b,rol='cliente',autenticado=true,origin='https://prueba.local'){
 let status,body;const headers={};const req={method:'POST',headers:{host:'prueba.local',origin,cookie:autenticado?'sunat_sesion='+crearToken(7,secreto):''},body:b};const res={setHeader:(k,v)=>headers[k]=v,status(n){status=n;return this},json(v){body=v;return this}};
 return handler(req,res).then(()=>({status,body,headers}));
}
function base(rol){const queries=[];const sql=async(strings,...values)=>{const text=strings.join('?');queries.push({text,values});if(text.includes('SELECT id,rol,turno FROM usuarios'))return [{id:7,rol,turno:'manana'}];if(text.startsWith('UPDATE solicitudes'))return [];return [];};return {sql,queries};}
test('Firma de sesión rechaza manipulación y otro secreto',()=>{const t=crearToken(7,secreto);assert.equal(leerToken(t,secreto),7);assert.equal(leerToken(t+'a',secreto),null);assert.equal(leerToken(t,'otro'),null);assert.equal(leerToken('roto',secreto),null);});
test('Contraseñas hash y compatibilidad Semana 6',()=>{const h=hashClave('1234');assert.equal(verificarClave('1234',h),true);assert.equal(verificarClave('0000',h),false);assert.equal(verificarClave('1234','1234'),true);assert.equal(verificarClave('0000','1234'),false);});
test('API bloquea visitante',async()=>{const b=base('cliente');const r=await ejecutar(crearHandler(b.sql,secreto,()=>new Date("2026-10-01T12:00:00Z")),{accion:'listarTodos'},'cliente',false);assert.equal(r.status,401);assert.equal(b.queries.length,0);});
test('Cliente no accede al panel aunque envíe rol falso',async()=>{const b=base('cliente');const r=await ejecutar(crearHandler(b.sql,secreto,()=>new Date("2026-10-01T12:00:00Z")),{accion:'eliminarPanel',id:1,rol:'administrador'});assert.equal(r.status,403);assert.equal(b.queries.length,1);});
test('Cliente solo consulta su id real de sesión',async()=>{const b=base('cliente');const r=await ejecutar(crearHandler(b.sql,secreto,()=>new Date("2026-10-01T12:00:00Z")),{accion:'misSolicitudes',id_usuario:99});assert.equal(r.status,200);assert.deepEqual(b.queries[1].values,[7]);});
test('UPDATE propio atómico con propietario y estado',async()=>{const b=base('cliente');const r=await ejecutar(crearHandler(b.sql,secreto,()=>new Date("2026-10-01T12:00:00Z")),{accion:'actualizarPropia',id:12,id_usuario:99,estado:'atendido',nombre_contribuyente:'Persona',ruc:'20123456789',correo:'prueba@example.com'});assert.equal(r.status,200);assert.deepEqual(r.body,[]);assert.match(b.queries[1].text,/id_usuario=\? AND estado='registrado'/);assert.equal(b.queries[1].values.at(-1),7);});
for(const rol of ['administrador','empleado'])test(rol+' puede listar y crear en panel',async()=>{const b=base(rol),handler=crearHandler(b.sql,secreto,()=>new Date("2026-10-01T12:00:00Z"));assert.equal((await ejecutar(handler,{accion:'listarTodos'})).status,200);assert.equal((await ejecutar(handler,{accion:'crearPanel',nombre_contribuyente:'Persona',ruc:'20123456789',correo:'prueba@example.com',estado:'registrado'})).status,200);assert.match(b.queries.at(-1).text,/INSERT INTO solicitudes_clave_sol/);assert.equal(b.queries.at(-1).text.includes('id_usuario'),false);});
test('Registro público ignora rol enviado y guarda hash',async()=>{const b=base('cliente');const r=await ejecutar(crearHandler(b.sql,secreto,()=>new Date("2026-10-01T12:00:00Z")),{accion:'registrarUsuario',nombre:'Persona',correo:'prueba@example.com',contrasena:'1234',rol:'administrador'},'cliente',false);assert.equal(r.status,200);assert.match(b.queries[0].text,/'cliente'/);assert.match(b.queries[0].values[2],/^scrypt\$/);});
test('Rechaza origen ajeno y SQL arbitrario',async()=>{const b=base('cliente'),handler=crearHandler(b.sql,secreto,()=>new Date("2026-10-01T12:00:00Z"));assert.equal((await ejecutar(handler,{accion:'listarTodos'},'cliente',true,'https://ajeno.local')).status,403);assert.equal((await ejecutar(handler,{accion:'ejecutarSQL',sql:'DROP TABLE usuarios'})).status,400);});

// Horario Lima: 06:00, 14:00, 22:00 y cruce de medianoche.
test('Límites de los tres turnos',async()=>{const {turnoActual,permisoTurno}=await import('../api/sunat.js');for(const [hora,esperado] of [['05:59','noche'],['06:00','manana'],['13:59','manana'],['14:00','tarde'],['21:59','tarde'],['22:00','noche'],['00:00','noche']]){const fecha=new Date('2026-10-01T'+hora+':00-05:00');assert.equal(turnoActual(fecha),esperado);assert.equal(permisoTurno({rol:'empleado',turno:esperado},fecha),true);assert.equal(permisoTurno({rol:'empleado',turno:'otro'},fecha),false);assert.equal(permisoTurno({rol:'administrador'},fecha),true);}});
test('Fuera del turno bloquea escritura y permite consulta',async()=>{const b=base('empleado'),handler=crearHandler(b.sql,secreto,()=>new Date('2026-10-01T20:00:00Z'));assert.equal((await ejecutar(handler,{accion:'eliminarPanel',id:1})).status,403);assert.equal((await ejecutar(handler,{accion:'listarTodos'})).status,200);});
